// Validation scenarios for uplink / optic selection. `expect` is what a ProAV designer would want to see.
const base = {region:'Americas',taa:false,psuRed:false,dualUplink:false,dualCore:false,basis:'line',oversub:1,spare:10,poeHead:20,
  voltage:110,gateway:false,support:0,family:'Auto',mdfPatch:3,coreOverride:'Auto',islRule:'half',psuScope:'all'};
const L = (name, type, distance, media, eps) => ({id:name, name, type, distance, media, override:'Auto', eps:eps.map(([ep,qty])=>({ep,qty}))});
const MDF = (eps=[]) => L('Main equipment room','MDF',3,'MMF',eps);
const S = (id, title, expect, project, locations) => ({id, title, expect, project:{...base, name:`${id} ${title}`, ...project}, locations});

module.exports = [
  S('V01','Screenshot case, single core',
    'Closet 2 (90G) must go 25G; Closet 3 (80G) may use 8x10G or 4x25G; Closet 4 1x10G. 25G SR optic, no placeholders.',
    {spare:0}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]]), L('Closet 4','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V02','Screenshot case, redundant core',
    'Same rooms with two cores: each core link group carries the full load. 100G core-to-core cable from catalog.',
    {spare:0, dualCore:true}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]]), L('Closet 4','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V03','25G over 150 m multimode',
    '25G SR reaches only 100 m (OM4). At 150 m the engine should stay on 10G SR (300 m) where it can, or flag that 25G needs single mode.',
    {spare:0}, [MDF(), L('Closet A','IDF',150,'MMF',[['EP-10G-TX',9]]), L('Closet B','IDF',150,'MMF',[['EP-10G-TX',4]])]),
  S('V04','25G over 600 m single mode',
    '600 m SMF: 25G LR (NGS25G-LR-OC) for the 90G closet, 10G LR (AXM762) for the small one.',
    {spare:0}, [MDF(), L('Closet A','IDF',600,'SMF',[['EP-10G-TX',9]]), L('Closet B','IDF',600,'SMF',[['EP-10G-TX',4]])]),
  S('V05','Big closet needs 100G, multimode',
    '~200G closet: 100G QSFP28 uplinks with SR4 (MPO) at 100 m, or several 25G links. No placeholders.',
    {spare:0}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-10G-TX',20]]), L('Closet B','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V06','Big closet needs 100G, 400 m single mode',
    '~200G at 400 m SMF: 100G LR4 (duplex LC) preferred over PSM4 (needs 8-fiber MPO trunk).',
    {spare:0}, [MDF(), L('Closet A','IDF',400,'SMF',[['EP-10G-TX',20]]), L('Closet B','IDF',400,'SMF',[['EP-1G-RX',8]])]),
  S('V07','Main room access switches, in-rack',
    'MDF access switches link to the core with in-rack DAC/AOC at the right speed (25G DAC if 25G).',
    {spare:0}, [MDF([['EP-10G-TX',40],['EP-1G-TX',24]])]),
  S('V08','ST 2110 25G fiber endpoints',
    '25G fiber endpoints get a 25G SR switch-side optic (NGS25G-SR-OC), not a placeholder.',
    {spare:0}, [MDF(), L('Studio','IDF',100,'MMF',[['EP-25G-2110',8],['EP-1G-TX',8]])]),
  S('V09','2:1 oversubscription',
    '90G of devices at 2:1 = 45G: 8x10G or 2x25G; never more capacity than needed at line-rate.',
    {spare:0, oversub:2}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet B','IDF',100,'MMF',[['EP-WBE758',8]])]),
  S('V10','Stream bandwidth basis',
    'Stream basis: 1G encoders count at stream rate, so small uplinks (1-2 x 10G).',
    {basis:'stream'}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-1G-TX',40],['EP-1G-RX',40]])]),
  S('V11','M4250 series only',
    'M4250 has no 25G: closets above 80G cannot fit; expect a clear message or split switches, never a 25G optic on M4250.',
    {spare:0, family:'M4250'}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-1G-RX',40]]), L('Closet B','IDF',100,'MMF',[['EP-1G-TX',16]])]),
  S('V12','Many 10G closets, core port pressure',
    'Six 60G closets: core runs out of SFP+ ports, engine should move to 25G/100G and a bigger core.',
    {spare:0, dualCore:true}, [MDF(), ...[1,2,3,4,5,6].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',6]]))]),
  S('V13','Redundant power, TAA, Europe',
    'Option check: TAA SKUs only, redundant PSUs, A4 report, EU SKUs. Uplinks as in V01.',
    {spare:0, region:'Europe', taa:true, psuRed:true, voltage:230}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]])]),
  S('V14','Dante audio only',
    'Audio only at 1G: low-cost 1G PoE+ switches (M4250), 1 x 10G uplinks. No M4350 needed.',
    {}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-DANTE',40]]), L('FOH','IDF',100,'MMF',[['EP-DANTE',16],['EP-PANEL',2]])]),
  S('V15','AVB / Milan audio, big room',
    'AVB on M4250 does not run over a LAG: a room needing more than one 10G uplink must use M4350 (or more M4250 with one uplink each).',
    {}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-MILAN',96]]), L('FOH','IDF',100,'MMF',[['EP-MILAN',8]])]),
  S('V16','ST 2110 with PTP boundary clock',
    'ST 2110 devices need a PTP boundary clock: room switch and core must be BC-capable M4350 models (16V4C / 40F4C / 24F4X / 24M4X4V...).',
    {spare:0}, [MDF(), L('Studio','IDF',100,'MMF',[['EP-25G-2110',8],['EP-1G-TX',4]]), L('Gallery','IDF',100,'MMF',[['EP-1G-RX',16]])]),
  S('V17','Dante audio, stream basis',
    'Stream basis: audio is ~20 Mb/s per device, so even a big audio room needs only 1 x 10G (or 2 with dual uplinks).',
    {basis:'stream', dualUplink:true}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-DANTE',80]])]),
];
