// Validation scenarios for uplink / optic selection. `expect` is what a ProAV designer would want to see.
const base = {region:'Americas',taa:false,psuRed:false,dualUplink:false,dualCore:false,basis:'line',oversub:1,spare:10,poeHead:20,
  voltage:110,gateway:false,support:'',family:'Auto',mdfPatch:3,coreOverride:'Auto',islRule:'half',psuScope:'all'};
const L = (name, type, distance, media, eps) => ({id:name, name, type, distance, media, override:'Auto', eps:eps.map(([ep,qty])=>({ep,qty}))});
const MDF = (eps=[]) => L('Main equipment room','MDF',3,'MMF',eps);
const S = (id, title, expect, project, locations, extraEndpoints=[]) => ({id, title, expect, project:{...base, name:`${id} ${title}`, ...project}, locations, extraEndpoints});
// device types a scenario needs that are not in the catalog library
const EP25FX = {Endpoint_ID:'EP-25G-FX', Name:'25G fiber device (SFP28)', Category:'Video', Link_Speed_Gbps:25, Media:'Fiber', PoE_W:0, Stream_Mbps:20000};

module.exports = [
  S('V01','Screenshot case, single core',
    'Closet 2 (90G) must go 25G; Closet 3 (80G) may use 8x10G or 4x25G; Closet 4 1x10G. 25G SR optic, no placeholders.',
    {spare:0}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]]), L('Closet 4','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V02','Screenshot case, redundant core',
    'Same rooms with two cores: each core link group carries the full load. 100G core-to-core cable from catalog.',
    {spare:0, dualCore:true}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]]), L('Closet 4','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V03','25G over 150 m multimode',
    '25G SR reaches only 100 m (OM4). At 150 m the engine should stay on 10G SR (300 m) where it can, or flag that 25G needs single mode.',
    {spare:0}, [MDF(), L('Closet A','IDF',150,'MMF',[['EP-10G-TX',9]]), L('Closet B','IDF',150,'MMF',[['EP-10G-TX',4]])]),
  S('V04','25G over 600 m single mode',
    '600 m SMF: 25G LR (NGS25G-LR-OC) for the 90G closet, 10G LR (AXM762) for the small one.',
    {spare:0}, [MDF(), L('Closet A','IDF',600,'SMF',[['EP-10G-TX',9]]), L('Closet B','IDF',600,'SMF',[['EP-10G-TX',4]])]),
  S('V05','Big closet needs 100G, multimode',
    '~200G closet: 100G QSFP28 uplinks with SR4 (MPO) at 100 m, or several 25G links. No placeholders.',
    {spare:0}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-10G-TX',20]]), L('Closet B','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V06','Big closet needs 100G, 400 m single mode',
    '~200G at 400 m SMF: 100G LR4 (duplex LC) preferred over PSM4 (needs 8-fiber MPO trunk).',
    {spare:0}, [MDF(), L('Closet A','IDF',400,'SMF',[['EP-10G-TX',20]]), L('Closet B','IDF',400,'SMF',[['EP-1G-RX',8]])]),
  S('V07','Main room access switches, in-rack',
    'MDF access switches link to the core with in-rack DAC/AOC at the right speed (25G DAC if 25G).',
    {spare:0}, [MDF([['EP-10G-TX',40],['EP-1G-TX',24]])]),
  S('V08','ST 2110 25G fiber endpoints',
    '25G fiber endpoints get a 25G SR switch-side optic (NGS25G-SR-OC), not a placeholder.',
    {spare:0}, [MDF(), L('Studio','IDF',100,'MMF',[['EP-25G-2110',8],['EP-1G-TX',8]])]),
  S('V09','2:1 oversubscription',
    '90G of devices at 2:1 = 45G: 8x10G or 2x25G; never more capacity than needed at line-rate.',
    {spare:0, oversub:2}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet B','IDF',100,'MMF',[['EP-WBE758',8]])]),
  S('V10','Stream bandwidth basis',
    'Stream basis: 1G encoders count at stream rate, so small uplinks (1-2 x 10G).',
    {basis:'stream'}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-1G-TX',40],['EP-1G-RX',40]])]),
  S('V11','M4250 series only',
    'M4250 has no 25G: closets above 80G cannot fit; expect a clear message or split switches, never a 25G optic on M4250.',
    {spare:0, family:'M4250'}, [MDF(), L('Closet A','IDF',100,'MMF',[['EP-1G-RX',40]]), L('Closet B','IDF',100,'MMF',[['EP-1G-TX',16]])]),
  S('V12','Many 10G closets, core port pressure',
    'Six 60G closets, redundant core: needs an M4500 core (48 x 25G); 25G optics must fit both M4350 and M4500.',
    {spare:0, dualCore:true}, [MDF(), ...[1,2,3,4,5,6].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',6]]))]),
  S('V13','Redundant power, TAA, Europe',
    'Option check: TAA SKUs only, redundant PSUs, A4 report, EU SKUs. Uplinks as in V01.',
    {spare:0, region:'Europe', taa:true, psuRed:true, voltage:230}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]])]),
  S('V14','Dante audio only',
    'Audio only at 1G: low-cost 1G PoE+ switches (M4250), 1 x 10G uplinks. No M4350 needed.',
    {}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-DANTE',40]]), L('FOH','IDF',100,'MMF',[['EP-DANTE',16],['EP-PANEL',2]])]),
  S('V15','AVB / Milan audio, big room',
    'AVB on M4250 does not run over a LAG: a room needing more than one 10G uplink must use M4350 (or more M4250 with one uplink each).',
    {}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-MILAN',96]]), L('FOH','IDF',100,'MMF',[['EP-MILAN',8]])]),
  S('V16','ST 2110 with PTP boundary clock',
    'ST 2110 devices need a PTP boundary clock: room switch and core must be BC-capable M4350 models (16V4C / 40F4C / 24F4X / 24M4X4V...).',
    {spare:0}, [MDF(), L('Studio','IDF',100,'MMF',[['EP-25G-2110',8],['EP-1G-TX',4]]), L('Gallery','IDF',100,'MMF',[['EP-1G-RX',16]])]),
  S('V17','Dante audio, stream basis',
    'Stream basis: audio is ~20 Mb/s per device, so even a big audio room needs only 1 x 10G (or 2 with dual uplinks).',
    {basis:'stream', dualUplink:true}, [MDF(), L('Stage','IDF',100,'MMF',[['EP-DANTE',80]])]),
  S('V18','M4500 spine and leaf, 10G fiber',
    'Six rooms of 40 x 10G fiber devices, redundant core: M4500-48XF8C leaves with 4 x 100G to each M4500-32C core (datasheet 320 x 320 style).',
    {spare:0, dualCore:true, islRule:'failover'}, [MDF(), ...[1,2,3,4,5,6].map(i=>L(`Leaf ${i}`,'IDF',100,'MMF',[['EP-10G-FX',40]]))]),
  S('V19','Ten 200G closets, single core',
    'Ten closets of 20 x 10G: 100G or 25G uplinks into an M4500 core; 100G optics must fit both ends (optic.ca when the closet is M4350).',
    {spare:0}, [MDF(), ...[1,2,3,4,5,6,7,8,9,10].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',20]]))]),
  S('V20','PR460X gateway',
    'Gateway on: PR460X connects to the core with 10G SR optics on both ends (no DAC), plus an LC patch cord note.',
    {spare:0, gateway:true}, [MDF(), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',9]]), L('Closet 3','IDF',100,'MMF',[['EP-WBE758',8]])]),
  S('V21','PR460X gateway, M4500 core',
    'Gateway on with an M4500 core: router link still uses AXM761 optics (fits PR460X and M4500), never a DAC.',
    {spare:0, gateway:true, dualCore:true}, [MDF(), ...[1,2,3,4,5,6].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',6]]))]),
  S('V22','M4500 as room switch, 25G fiber',
    'Two rooms of 20 x 25G fiber devices (no timing need): M4500-48XF8C or M4350-16V4C with 100G uplinks, core terminates 100G only.',
    {spare:0}, [MDF(), L('Render A','IDF',100,'MMF',[['EP-25G-FX',20]]), L('Render B','IDF',100,'MMF',[['EP-25G-FX',20]])], [EP25FX]),
  S('V23','Many 100G links plus a 10G closet (known gap)',
    'Known gap: 12 x 100G plus 10G links need QSFP28 breakout on the core, which the engine does not model. Expect a clear error, not a wrong design.',
    {spare:0}, [MDF(), L('Render farm','IDF',100,'MMF',[['EP-25G-FX',40]]), L('Office','IDF',100,'MMF',[['EP-1G-TX',8]])], [EP25FX]),
  S('V24','100G closets with gateway, M4500-32C core',
    'M4350-40X4C closets on 4 x 100G into an M4500-32C. The core has no 10G port, so the PR460X goes on a free 10G copper port of a closet switch (Cat6a within 100 m).',
    {gateway:true, psuRed:true, dualUplink:true, spare:10}, [MDF(), L('Closet 1','IDF',100,'MMF',[['EP-10G-TX',60],['EP-10G-RX',10]]), L('Closet 2','IDF',100,'MMF',[['EP-10G-TX',20],['EP-10G-RX',8]]), L('Closet 3','IDF',100,'MMF',[['EP-10G-TX',28]])]),
  S('V25','Default demo design',
    'The app\'s default rooms with gateway: core box lists the 10G links per room and the router link, and the BoM books the core-end optics in the core.',
    {gateway:true, psuRed:true, dualUplink:true, spare:10}, [L('Main equipment room','MDF',3,'MMF',[['EP-1G-TX',16],['EP-10G-TX',4],['EP-DANTE',8]]), L('Closet 1','IDF',150,'MMF',[['EP-1G-RX',24],['EP-PTZ',4],['EP-WBE758',4]]), L('Closet 2','IDF',600,'SMF',[['EP-1G-RX',12],['EP-10G-FX',4],['EP-PANEL',6]])]),
  S('V26','8 Dante, one switch, gateway, redundant power',
    'Redundant power on: M4250 10-port models have one fixed PSU, so the M4350-8M2V is the smallest fit. Router on its free 10G fiber port.',
    {gateway:true, psuRed:true, spare:0, poeHead:0}, [MDF([['EP-DANTE',8]])]),
  S('V27','8 Dante, one switch, gateway, no redundant power',
    'Redundant power off: smallest M4250 (9G1F-PoE+). No 10G port free, so the router uses a free 1G copper port.',
    {gateway:true, psuRed:false, spare:0, poeHead:0}, [MDF([['EP-DANTE',8]])]),
  S('V28','8 Dante + 1 controller on an M4250-9G1F (fixed), gateway',
    'All copper ports used: router link falls back to a 1G SFP module (AGM731F) on both ends, with an alert to confirm 1G on the PR460X SFP+ port.',
    {gateway:true, psuRed:false, spare:0, poeHead:0}, [{...MDF([['EP-DANTE',8],['EP-CTRL',1]]), override:'GSM4210PD'}]),
  S('V29','Dante in two rooms, stream basis, collapsed core',
    'Seven Dante devices per room on stream bandwidth: 1G switches with a 1G SFP uplink, the main-room switch is also the core (no separate core switch), router on a 1G copper port with an alert.',
    {gateway:true, psuRed:false, basis:'stream', spare:0, poeHead:0}, [MDF([['EP-DANTE',7]]), L('Closet 1','IDF',100,'MMF',[['EP-DANTE',7]])]),
  S('V30','Dante + 1G video, line-rate, collapsed core',
    'Main room 7 Dante, closet 7 x 1G video decoders at line-rate: 10G SFP+ uplink, main-room M4250-8G2XF is also the core, router on its second SFP+.',
    {gateway:true, psuRed:false, spare:0, poeHead:0}, [MDF([['EP-DANTE',7]]), L('Closet 1','IDF',100,'MMF',[['EP-1G-RX',7]])]),
  S('V31','Router link: best available in main room',
    'One Dante device in the main room (redundant power: M4350-8M2V, also the core), two closets on 10G. Its SFP28 ports carry the closets, so the router uses a free 2.5G copper port on the 8M2V, not a closet switch 100 m away.',
    {gateway:true, psuRed:true, gwLink:'best'}, [MDF([['EP-DANTE',1]]), L('Closet 1','IDF',100,'MMF',[['EP-1G-RX',8]]), L('Closet 2','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V32','Router link: 10G required',
    'Same rooms with "10G required": the main-room switch must keep a 10G port for the router, so a larger switch (M4350-24G4XF) becomes the core and the router gets 10G SFP+.',
    {gateway:true, psuRed:true, gwLink:'10g'}, [MDF([['EP-DANTE',1]]), L('Closet 1','IDF',100,'MMF',[['EP-1G-RX',8]]), L('Closet 2','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V33','Overdrive 3 years on the demo design',
    'Support contract Overdrive 3 years: one DRV-<model>-36 SKU per switch, access point and router; core-end and room switches each get their own.',
    {gateway:true, psuRed:true, dualUplink:true, spare:10, support:'DRV:3'}, [L('Main equipment room','MDF',3,'MMF',[['EP-1G-TX',16],['EP-10G-TX',4],['EP-DANTE',8]]), L('Closet 1','IDF',150,'MMF',[['EP-1G-RX',24],['EP-PTZ',4],['EP-WBE758',4]]), L('Closet 2','IDF',600,'SMF',[['EP-1G-RX',12],['EP-10G-FX',4],['EP-PANEL',6]])]),
  S('V34','Fastlane on an M4500 design',
    'Fastlane is not listed for M4500: a warning and no support SKU for those switches (M4350 closets still get FLS SKUs).',
    {spare:0, dualCore:true, support:'FLS:1'}, [MDF(), ...[1,2,3,4,5,6].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',6]]))]),
  S('V35','Neutrik stage rack, redundant power',
    'Stage room set to Neutrik, uplink card opticalCON QUAD chosen: 8 Dante + 4 PTZ cameras on an M4350-16M4V (built-in 1+1 PSUs); its fiber uplink uses the APM414SD opticalCON QUAD card with optics inside, plus a note for the opticalCON field cables. The closet with standard connectors keeps a standard switch.',
    {gateway:true, psuRed:true, spare:10}, [MDF([['EP-DANTE',4]]), {...L('Stage','IDF',80,'MMF',[['EP-DANTE',8],['EP-PTZ',4]]), conn:'neutrik', card:'quad'}, L('Closet 1','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V36','100G closets, single core',
    'Four closets of 20 x 10G video: the smallest core that terminates everything. The engine fills an M4350-16V4C (2 closets on 100G, 2 on 25G) rather than buying an M4350-16C; optic.ca SR4 for 100G (ACM761 is M4500 only).',
    {spare:0}, [MDF(), ...[1,2,3,4].map(i=>L(`Closet ${i}`,'IDF',100,'MMF',[['EP-10G-TX',20]]))]),
  S('V37','ST 2110-30 audio with Dante',
    'One studio with ST 2110-30 / AES67 audio (PTP boundary clock) and Dante: all fits on one boundary-clock switch (M4350-24M4X4V), standalone.',
    {spare:0}, [MDF(), L('Studio','IDF',100,'MMF',[['EP-2110-AUDIO',8],['EP-DANTE',16]])]),
  S('V38','Neutrik stage rack, standard uplink card',
    'Same stage set to Neutrik, uplink card left at the default: the M4350-16M4V keeps its APM414V (SFP28, LC), no opticalCON card in the BoM.',
    {gateway:true, psuRed:true, spare:10}, [MDF([['EP-DANTE',4]]), {...L('Stage','IDF',80,'MMF',[['EP-DANTE',8],['EP-PTZ',4]]), conn:'neutrik'}, L('Closet 1','IDF',100,'MMF',[['EP-1G-RX',8]])]),
  S('V39','Prefer 25G, one closet beyond multimode reach',
    'Uplink speed "Prefer 25G": closets move to 25G-capable switches. Closet 2 (600 m SMF) gets the optic.ca 25G LR; Closet 1 (150 m MMF) gets a placeholder naming a third-party 25GBASE-eSR module (300 m on OM4), with a warning.',
    {spare:0, upSpeed:'25'}, [MDF(), L('Closet 1','IDF',150,'MMF',[['EP-1G-TX',10]]), L('Closet 2','IDF',600,'SMF',[['EP-1G-TX',15]])]),
];
